--SQLQuery0 - Create DB
CREATE DATABASE PV_521_DDL ON 
(
	NAME = PV_521_DDL,
	FILENAME = 'E:\Microsoft SQL Server\MSSQL16.TEST\MSSQL\DATA\PV_521_DDL.mdf',
	SIZE = 8 MB,
	MAXSIZE = 500 MB,
	FILEGROWTH = 8 MB
)

LOG ON 
(
	NAME = PV_521_DDL_Log,
	FILENAME = 'E:\Microsoft SQL Server\MSSQL16.TEST\MSSQL\DATA\PV_521_DDL.ldf',
	SIZE = 8 MB,
	MAXSIZE = 500 MB,
	FILEGROWTH = 8 MB
)